name: release-please
on:
  # !Option 1: Manual Trigger from GitHub
  # workflow_dispatch:
  # !Option 2: Release on every push on main branch
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
